variables:
  FRONTEND_DIR: "/home/agent4mpgp/mpgp/WebApiServer/WebApiServer/bin/Release/netcoreapp2.0/wwwroot"

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - build/

stages:
    - build
    - deploy

build:
    stage: build
    script:
    - rm -rf node_modules
    - npm install
    - npm run build

deploy:
    stage: deploy
    script:
    - rm -rf $FRONTEND_DIR/static
    - cp -rf ./build/* $FRONTEND_DIR/